### ISSUE TITLE
FoldGO Error in .local(.Object, ...) : allGenes must be a factor with 2 levels

### ISSUE THREAD

**Issue by krthkkrv** [DanWiebe/FoldGO#2]
Im using FoldGO to do fold specific GO analysis. Mine is a non-model bacterial organism and I am using .gaf file generated using blast2go for GO annotations.  I get an Error in .local(.Object, ...) : allGenes must be a factor with 2 levels when I use this code.

>library(FoldGO)
>genes <- readxl::read_xls("output_nt.xls")
> head(genes)
    Locus tag              Gene log2FoldChange     pvalue
1 AA042_00005 CP017687.1_gene_1      0.3418154 0.02204992
2 AA042_00010 CP017687.1_gene_2      0.1970550 0.13765894
3 AA042_00015 CP017687.1_gene_3      0.2494019 0.16217683
4 AA042_00020 CP017687.1_gene_4      0.2665905 0.07364455
5 AA042_00025 CP017687.1_gene_5      0.1610849 0.16230843
6 AA042_00030 CP017687.1_gene_6      0.1373724 0.46545317
        padj
1 0.07318019
2 0.25596327
3 0.28789531
4 0.16566421
5 0.28799771
6 0.59202987

>#getting DGE
>DGEgenes <- genes[which(genes$padj<0.1),]
> head(DGEgenes)
     Locus tag               Gene log2FoldChange       pvalue
1  AA042_00005  CP017687.1_gene_1      0.3418154 0.0220499249
16 AA042_00080 CP017687.1_gene_16     -0.7909870 0.0009165588
17 AA042_00085 CP017687.1_gene_17      0.4105026 0.0150500804
18 AA042_00090 CP017687.1_gene_18      0.3544752 0.0050537698
19 AA042_00095 CP017687.1_gene_19      0.4628939 0.0092474492
20 AA042_00100 CP017687.1_gene_20      0.3933930 0.0201835966
          padj
1  0.073180186
16 0.006782223
17 0.056724855
18 0.025688028
19 0.039995678
20 0.069364589

>#separating up regulated and down regulated gens
>up_genes <- DGEgenes[DGEgenes$log2FoldChange>0,]
>up_genes <- up_genes[,2:5]
> head(up_genes)
                 Gene log2FoldChange      pvalue       padj
1   CP017687.1_gene_1      0.3418154 0.022049925 0.07318019
17 CP017687.1_gene_17      0.4105026 0.015050080 0.05672485
18 CP017687.1_gene_18      0.3544752 0.005053770 0.02568803
19 CP017687.1_gene_19      0.4628939 0.009247449 0.03999568
20 CP017687.1_gene_20      0.3933930 0.020183597 0.06936459
21 CP017687.1_gene_21      0.3919965 0.027478649 0.08526021
>down_genes <- DGEgenes[DGEgenes$log2FoldChange<0,]
>down_genes <- down_genes[,2:5]

>up_groups <- GeneGroups(up_genes, quannumber = 2, logfold = T)
>down_groups <- GeneGroups(down_genes,quannumber = 2)

>#getting in the GO annotation form Blast2GO
>gaf <- GAFReader(file = "blast2gonh_gaf.txt")
>getVersion(gaf)
[1] "2.0"

>#creating object
> up_annotobj <- FuncAnnotGroupsTopGO(genegroups = up_groups, 
                                    namespace = "MF", 
                                    mapping = "manual",
                                    customAnnot = gaf, 
                                    annot = topGO::annFUN.GO2genes)

Error in .local(.Object, ...) : allGenes must be a factor with 2 levels

What did I miss?

Thank you in advance.

**Comment by DanWiebe** [comment]
Hi @krthkkrv!
It is necessary to provide a vector which contains background genes (e.g. all genes from your output_nt.xls file) as a `bggenes` parameter in `FuncAnnotGroupsTopGO` function. Note that if you are using custom annotation you have to set `mapping` parameter to `custom` instead of `manual`. So the code must be the following: 

> `up_annotobj <- FuncAnnotGroupsTopGO(genegroups = up_groups,
namespace = "MF",
mapping = "custom",
customAnnot = gaf,
annot = topGO::annFUN.GO2genes,
bggenes = genes$Gene)`

Feel free to ask me if something will not work.
Thank You for using FoldGO!

**Comment by krthkkrv** [comment]
It worked! Thank you.

**Comment by septav** [comment]
Hi!
I am getting the same error:Error in .local(.Object, ...) : allGenes must be a factor with 2 levels
 when running this command:


> library("org.Hs.eg.db")
> FuncAnnotGroupsTopGO(genegroups = up_groups,namespace ="MF", mapping = "org.Hs.eg.db", annot = topGO::annFUN.org, ID = "ensembl", bggenes = bggenes_hum)
> 

I am not sure if it the problem with "bggenes =  bggenes_hum" or if there is another problem.
I appreciate your help in advance:)
Thanks.

**Comment by DanWiebe** [comment]
Hi, septav!
It seems that the error occurs because you use here builtin example ```up_groups``` object which contains gene groups for A.thaliana with annotation and background gene set for human. Try to use code from the vignette:
```
up_groups <- GeneGroups(degenes_hum, quannumber=6)
FuncAnnotGroupsTopGO(up_groups,"MF", mapping = "org.Hs.eg.db", annot = topGO::annFUN.org, ID = "ensembl", bggenes = bggenes_hum)
```
All the best, Daniil Wiebe

**Comment by septav** [comment]
Hi DanWiebe, 

Thanks for response. Yes it is solved now.
I appreciate you help.

Best, 
Sep
