### ISSUE TITLE
possible bug in FoldSpecTest() : Error in stats::fisher.test(): all entries of 'x' must be nonnegative and finite

### ISSUE THREAD

**Issue by s-christel** [DanWiebe/FoldGO#4]
Hi!

I wrote a script earlier that uses FoldGO to analyze some data sets. All data sets have the same format and work just fine, one however, throws an error when going through FoldSpecTest() using the downregulated genes. Here are my commands leading up to the error. I can provide more details if necessary.

```
> foldGO_groups_down <- GeneGroups(minimal_GOfiltered_down %>% filter(Student.s.T.test.Difference < 0 & Student.s.T.test.q.value < pq_value_cutoff), quannumber=number_of_quantiles, logfold=T)
> foldGO_annotobj_down <- FuncAnnotGroupsTopGO(genegroups = foldGO_groups_down, bggenes = foldGO_background_genes, namespace = "BP", statistic = stat, mapping = "custom", customAnnot = ID2GO_map, annot = topGO::annFUN.GO2genes)

Building most specific GOs ..... (rest of output omitted)
> foldGO_foldspecific_down <- FoldSpecTest(foldGO_annotobj_down, fdrstep1 = 0.05, fdrstep2 = 0.01)
Error in stats::fisher.test(matrix(c(x[1], x[2] - x[1], x[3] - x[1], x[4] -  : 
  all entries of 'x' must be nonnegative and finite
```

I found this discussion online which I think may be relevant:
https://stackoverflow.com/questions/29214222/error-all-entries-of-x-must-be-nonnegative-and-finite-in-fisher-test

cheers,
stephan

**Comment by DanWiebe** [comment]
Hello!
Thank you for using FoldGO in your research. Could you please share expression data along with the annotation map? Or foldGO_annotobj_down object as an RDS file?
Kind regards, Daniil Wiebe

**Comment by s-christel** [comment]
Sorry for the very late response. I can't upload the dataset at this time, but I resolved the issue by changing the values of the fdrsteps.

**Comment by DanWiebe** [comment]
Thank you for the response! Anyway, I'll try to find out what caused the error. Can you tell me please to which values you have changed the fdrsteps?
Cheers, Daniil

**Comment by s-christel** [comment]
I used the default values at first, then changed to these:

step1 <- 1
step2 <- 0.05
foldGO_foldspecific_up <- FoldSpecTest(foldGO_annotobj_up, fdrstep1 = step1, fdrstep2 = step2)

**Comment by DanWiebe** [comment]
Thank you! Probably there were no significant GO terms with the fdrstep1 threshold set to 0.01. I will add error handling for such a case.
All the best, Daniil Wiebe
